
import '../../../../css/UIDashboard/Components.css'
function Components() {

    return (
          <>
        <div id="Components" >
            <table>
                <thead>
                    <th>ID</th>
                    <th>ModuleName</th>
                    <th>ComponentName</th>
                    <th>SubComponent</th>
                </thead>
                <tbody>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>AddActivity</td>
                    <td>10</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>EditActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ModifyActivity</td>
                    <td>14</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                    <tr>
                    <td>1</td>
                    <td>Activity</td>
                    <td>ClearActivity</td>
                    <td>4</td>
                    </tr>
                </tbody>
            </table>

        </div>
    </>
    )
    
}
export default Components;